@localhost=localhost:4004/odata/v4/main
@id=a2bca205-689a-465a-8e17-c7489ab17b94
@customerId=7643391f-968d-4210-9490-36f6da431dde
@productId=7501a9ee-0142-459d-a6a0-2d5891a70eb4

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 35.88,
    "items": [
        {
            "id": "44828c87-565b-4592-9e4e-ff9f142ceece",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 2,
            "price": 2.99
        },
        {
            "id": "76fd9d77-6b67-4ed6-b262-b908f50eb8c7",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json

{
    "modifiedBy": "test"
}

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 200000&$expand=items($expand=product),customer
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 200000&$expand=items($expand=product;$filter=quantity le 30),customer
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$skip=1&$top=5
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$search=3orua&$filter= totalAmount ge 200000
Content-Type: application/json