@localhost=localhost:4004/odata/v4/main

GET http://{localhost}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{localhost}/SalesOrderHeaders
Content-Type: application/json

{
}

###

DELETE http://{localhost}/SalesOrderHeaders(515b838f-607b-4f85-a1c2-75434c5e7696)
Content-Type: application/json

###

PUT http://{localhost}/SalesOrderHeaders(adfac79f-51ee-46ae-9920-8e78aaa4fc24)
Content-Type: application/json

{
    modifiedBy: "test"
}